[project]
name = "fastpy-xlsx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "databases[aiomysql]>=0.9.0",
    "fastapi>=0.115.14",
    "openpyxl>=3.1.5",
    "uvicorn[standard]>=0.35.0",
    "xlsxwriter>=3.2.5",
]
